// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/12/2025, 4:16:20 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/marquisabah/Documents/groCart/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/groCart/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/groCart/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/groCart/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/groCart/plugins/**/*.{js,ts,mjs}","/Users/marquisabah/Documents/groCart/composables/**/*.{js,ts,mjs}","/Users/marquisabah/Documents/groCart/utils/**/*.{js,ts,mjs}","/Users/marquisabah/Documents/groCart/pages/index.vue","/Users/marquisabah/Documents/groCart/pages/login.vue","/Users/marquisabah/Documents/groCart/pages/signup.vue","/Users/marquisabah/Documents/groCart/pages/verify.vue","/Users/marquisabah/Documents/groCart/pages/store/[id].vue","/Users/marquisabah/Documents/groCart/pages/store/index.vue","/Users/marquisabah/Documents/groCart/pages/product/[id].vue","/Users/marquisabah/Documents/groCart/pages/dashboard/index.vue","/Users/marquisabah/Documents/groCart/pages/dashboard/users.vue","/Users/marquisabah/Documents/groCart/pages/dashboard/vendors.vue","/Users/marquisabah/Documents/groCart/pages/dashboard/shoppers.vue","/Users/marquisabah/Documents/groCart/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/groCart/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marquisabah/Documents/groCart/app.config.{js,ts,mjs}","/Users/marquisabah/Documents/groCart/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;